// <auto-generated />
using System;
using MealPlannerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealPlannerApi.Migrations
{
    [DbContext(typeof(MealPlannerDbContext))]
    [Migration("20260415231243_AddRichNutritionTables")]
    partial class AddRichNutritionTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MealPlannerApi.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumToegevoegd")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("UserId", "MealId")
                        .IsUnique();

                    b.ToTable("Favorites", (string)null);
                });

            modelBuilder.Entity("MealPlannerApi.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Caloriedoel")
                        .HasColumnType("double")
                        .HasColumnName("CalorieDoel");

                    b.Property<double>("Eiwitdoel")
                        .HasColumnType("double")
                        .HasColumnName("EiwitDoel");

                    b.Property<double>("Koolhydraatdoel")
                        .HasColumnType("double")
                        .HasColumnName("KoolhydraatDoel");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("Vetdoel")
                        .HasColumnType("double")
                        .HasColumnName("VetDoel");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Goals", (string)null);
                });

            modelBuilder.Entity("MealPlannerApi.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Eenheid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients", (string)null);
                });

            modelBuilder.Entity("MealPlannerApi.Models.IngredientNutrientValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientNutritionMappingId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEstimated")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NutrientDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<double>("ValuePer100g")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("NutrientDefinitionId");

                    b.HasIndex("IngredientNutritionMappingId", "NutrientDefinitionId")
                        .IsUnique();

                    b.ToTable("IngredientNutrientValues", (string)null);
                });

            modelBuilder.Entity("MealPlannerApi.Models.IngredientNutritionMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalDataType")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("ExternalFoodDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ExternalFoodId")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEstimated")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("MatchScore")
                        .HasColumnType("double");

                    b.Property<DateTime>("MatchedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId", "Source")
                        .IsUnique();

                    b.ToTable("IngredientNutritionMappings", (string)null);
                });

            modelBuilder.Entity("MealPlannerApi.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AfbeeldingUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Bereidingstijd")
                        .HasColumnType("int");

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DieetLabels")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ExternalMealDbId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Instructies")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Porties")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("ExternalMealDbId")
                        .IsUnique();

                    b.ToTable("Meals", (string)null);
                });

            modelBuilder.Entity("MealPlannerApi.Models.MealIngredient", b =>
                {
                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<double>("Hoeveelheid")
                        .HasColumnType("double");

                    b.Property<string>("OrigineleHoeveelheid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MealId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("MealIngredients", (string)null);
                });

            modelBuilder.Entity("MealPlannerApi.Models.NutrientDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("DailyValue")
                        .HasColumnType("double");

                    b.Property<double>("DisplayOrder")
                        .HasColumnType("double");

                    b.Property<bool>("Highlight")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("NutrientDefinitions", (string)null);
                });

            modelBuilder.Entity("MealPlannerApi.Models.NutrientExternalId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalNutrientNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("NutrientDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("NutrientDefinitionId");

                    b.HasIndex("Source", "ExternalNutrientNumber")
                        .IsUnique();

                    b.ToTable("NutrientExternalIds", (string)null);
                });

            modelBuilder.Entity("MealPlannerApi.Models.NutritionalValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Eiwit")
                        .HasColumnType("double")
                        .HasColumnName("Eiwitten");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<double>("Kcal")
                        .HasColumnType("double")
                        .HasColumnName("Calorieen");

                    b.Property<double>("Koolhydraat")
                        .HasColumnType("double")
                        .HasColumnName("Koolhydraten");

                    b.Property<double>("Vet")
                        .HasColumnType("double")
                        .HasColumnName("Vetten");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId")
                        .IsUnique();

                    b.ToTable("NutritionalValues", (string)null);
                });

            modelBuilder.Entity("MealPlannerApi.Models.PlannedMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("GeplandeDatum");

                    b.Property<string>("Maaltijdtype")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TypeMaaltijd");

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("UserId", "Datum", "Maaltijdtype")
                        .IsUnique();

                    b.ToTable("PlannedMeals", (string)null);
                });

            modelBuilder.Entity("MealPlannerApi.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Activiteit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Allergieen")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Dieetvoorkeur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("Gewicht")
                        .HasColumnType("double");

                    b.Property<int>("Leeftijd")
                        .HasColumnType("int");

                    b.Property<double>("LengteCm")
                        .HasColumnType("double");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("MealPlannerApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("User");

                    b.Property<string>("WachtwoordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MealPlannerApi.Models.Favorite", b =>
                {
                    b.HasOne("MealPlannerApi.Models.Meal", "Meal")
                        .WithMany("Favorites")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPlannerApi.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlannerApi.Models.Goal", b =>
                {
                    b.HasOne("MealPlannerApi.Models.User", "User")
                        .WithOne("Goal")
                        .HasForeignKey("MealPlannerApi.Models.Goal", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlannerApi.Models.IngredientNutrientValue", b =>
                {
                    b.HasOne("MealPlannerApi.Models.IngredientNutritionMapping", "IngredientNutritionMapping")
                        .WithMany("NutrientValues")
                        .HasForeignKey("IngredientNutritionMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlannerApi.Models.NutrientDefinition", "NutrientDefinition")
                        .WithMany("IngredientNutrientValues")
                        .HasForeignKey("NutrientDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IngredientNutritionMapping");

                    b.Navigation("NutrientDefinition");
                });

            modelBuilder.Entity("MealPlannerApi.Models.IngredientNutritionMapping", b =>
                {
                    b.HasOne("MealPlannerApi.Models.Ingredient", "Ingredient")
                        .WithMany("NutritionMappings")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("MealPlannerApi.Models.MealIngredient", b =>
                {
                    b.HasOne("MealPlannerApi.Models.Ingredient", "Ingredient")
                        .WithMany("MealIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPlannerApi.Models.Meal", "Meal")
                        .WithMany("MealIngredients")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("MealPlannerApi.Models.NutrientExternalId", b =>
                {
                    b.HasOne("MealPlannerApi.Models.NutrientDefinition", "NutrientDefinition")
                        .WithMany("ExternalIds")
                        .HasForeignKey("NutrientDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NutrientDefinition");
                });

            modelBuilder.Entity("MealPlannerApi.Models.NutritionalValue", b =>
                {
                    b.HasOne("MealPlannerApi.Models.Ingredient", "Ingredient")
                        .WithOne("NutritionalValue")
                        .HasForeignKey("MealPlannerApi.Models.NutritionalValue", "IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("MealPlannerApi.Models.PlannedMeal", b =>
                {
                    b.HasOne("MealPlannerApi.Models.Meal", "Meal")
                        .WithMany("PlannedMeals")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPlannerApi.Models.User", "User")
                        .WithMany("PlannedMeals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlannerApi.Models.Profile", b =>
                {
                    b.HasOne("MealPlannerApi.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("MealPlannerApi.Models.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlannerApi.Models.Ingredient", b =>
                {
                    b.Navigation("MealIngredients");

                    b.Navigation("NutritionMappings");

                    b.Navigation("NutritionalValue");
                });

            modelBuilder.Entity("MealPlannerApi.Models.IngredientNutritionMapping", b =>
                {
                    b.Navigation("NutrientValues");
                });

            modelBuilder.Entity("MealPlannerApi.Models.Meal", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("MealIngredients");

                    b.Navigation("PlannedMeals");
                });

            modelBuilder.Entity("MealPlannerApi.Models.NutrientDefinition", b =>
                {
                    b.Navigation("ExternalIds");

                    b.Navigation("IngredientNutrientValues");
                });

            modelBuilder.Entity("MealPlannerApi.Models.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Goal");

                    b.Navigation("PlannedMeals");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
